server:
  port: 8888
spring:
  application:
    name: barbosa-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GiselleBarbosa/barbosa-config-server
          default-label: main
          search-paths:
            - 'greeting-service'
